function [BW,maskedImage] = segmentDeforestationIntensity(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 26-Mar-2025
%----------------------------------------------------


% Threshold image with manual threshold
BW = im2gray(X) > 204;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

